%DEMO_TOOLBAR_REWORK Demo for the reworked dashboard toolbar.
%
%   Exercises the toolbar + config + stale-banner behaviors:
%     1. Info button is always present — click it with no InfoFile set
%        to see the built-in placeholder page.
%     2. Config button opens a dialog for every public engine property
%        (Name, Theme, LiveInterval, InfoFile, ProgressMode,
%        ShowTimePanel). Hover each field for its tooltip. Use Browse…
%        next to InfoFile to pick a Markdown file. Apply to commit.
%     3. Live button gets a solid blue border when toggled on.
%     4. Stale-data banner: this demo uses a FastSense widget backed by
%        a SensorTag whose time-series data does NOT advance during
%        live mode. Click Live and after one LiveInterval the amber
%        warning banner appears right under the toolbar — because
%        tMax did not increase.
%
%   Usage:
%     >> run('examples/demo_toolbar_rework.m')

close all force;

% Pre-seeded sensor with a fixed time range — during live mode, its
% tMax will stay constant and trigger the stale-data banner.
nSeed = 200;
tSeed = linspace(-20, 0, nSeed);
sFrozen = SensorTag('DEMO-T', 'Name', 'Frozen Temp', 'Units', 'C', ...
    'X', tSeed, 'Y', 20 + sin(2*pi*tSeed/10) + randn(1, nSeed)*0.3);

d = DashboardEngine('Toolbar Rework Demo', 'LiveInterval', 2.0);

d.addWidget('fastsense', ...
    'Title',    'Frozen sensor (no new data)', ...
    'Position', [1 1 8 4], ...
    'Tag',      sFrozen);

d.addWidget('number', ...
    'Title',    'Random value', ...
    'Position', [9 1 4 2], ...
    'ValueFcn', @() randn(), ...
    'Format',   '%.3f');

d.addWidget('text', ...
    'Title',    'Instructions', ...
    'Position', [1 5 12 4], ...
    'Content',  sprintf([ ...
        '**Try the toolbar:**\n\n', ...
        '1. Hover every button and every Config field — all have tooltips.\n\n', ...
        '2. Click **Config** — try Theme → dark, Apply. Uncheck ShowTimePanel, Apply.\n\n', ...
        '3. Click **Info** — placeholder page opens (no InfoFile configured).\n\n', ...
        '4. Click **Live** — blue border appears. After ~2s the amber banner ', ...
        'shows "No new data received in the last 2s" because the frozen sensor ', ...
        'does not advance. Click Live again to stop.']));

d.render();
disp('Demo ready — try Config, Live, Info, and hover the controls.');
